name: prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: 
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            node -v
            cd ~/32dentplus
            git pull origin main
            yarn install
            yarn build
            kill -9 `lsof -t -i:80`
            yarn start -p 80 & bg
